/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/invites/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_checkInvite_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-in-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_sendSignInCode_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifySignInCode_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["DevicesController_register_v1"];
        post?: never;
        delete: operations["DevicesController_unregister_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/legal/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LegalController_current_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_get_v1"];
        put?: never;
        post?: never;
        delete: operations["MeController_deleteAccount_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MeController_updateProfile_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MeController_changePin_v1"];
        post: operations["MeController_createPin_v1"];
        delete: operations["MeController_removePin_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/pin/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MeController_checkPin_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getWallet_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getTransactions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_lookup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/printed-qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_createPrintedQrPayment_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_confirm_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_status_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/for-request/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_statusForRequest_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payment-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShopPaymentsController_createRequest_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payment-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopPaymentsController_requestStatus_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/pending-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopPaymentsController_pending_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payments/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShopPaymentsController_accept_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payments/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShopPaymentsController_decline_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PartnersController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopsController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/favourites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopsController_favourites_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/favourites/{shopId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ShopsController_addFavourite_v1"];
        post?: never;
        delete: operations["ShopsController_removeFavourite_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopsController_placements_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopsController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/support/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SupportController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: Record<string, never>;
        CheckInviteDto: {
            /** @example KOLL2026 */
            code: string;
        };
        InviteDto: {
            code: string;
            employerName: string;
            email: string;
            firstName: string;
            lastName: string;
        };
        SendSignInCodeDto: {
            /** @example max.mustermann@muster-gmbh.example */
            email: string;
            /** @description Set when signing up with an employer invite. */
            inviteCode?: string;
            /**
             * @description Which app signs in: the employee app (default) or the shop portal. Each only accepts its own people.
             * @enum {string}
             */
            app?: "employee" | "shop";
        };
        VerifySignInCodeDto: {
            /** @example max.mustermann@muster-gmbh.example */
            email: string;
            /** @description Set when signing up with an employer invite. */
            inviteCode?: string;
            /**
             * @description Which app signs in: the employee app (default) or the shop portal. Each only accepts its own people.
             * @enum {string}
             */
            app?: "employee" | "shop";
            /** @example 246813 */
            code: string;
        };
        MeDto: {
            id: string;
            email: string;
            employerName: string;
            firstName: string;
            lastName: string;
            hasCompletedProfile: boolean;
            hasPaymentPin: boolean;
            /** @enum {string} */
            status: "active" | "ended" | "blocked";
            /** @description Set while leaving: last day the balance can be used (YYYY-MM-DD). */
            benefitEndsAt: Record<string, never> | null;
            /** @description Employer's workplace; distances are measured from here without location sharing. */
            workplaceLatitude: Record<string, never> | null;
            workplaceLongitude: Record<string, never> | null;
        };
        SessionDto: {
            /** @description Exchange with Firebase signInWithCustomToken, then send the ID token as Bearer. */
            firebaseCustomToken: string;
            user: components["schemas"]["MeDto"];
        };
        RegisterDeviceDto: {
            /** @description Firebase Cloud Messaging token */
            pushToken: string;
            /** @enum {string} */
            platform: "ios" | "android";
            /** @enum {string} */
            language: "de" | "en";
            /** @example 0.1.0 */
            appVersion?: string;
        };
        LegalDocumentDto: {
            /** @enum {string} */
            type: "terms" | "privacy";
            /** @example 2026-10 */
            version: string;
            /** @example de */
            language: string;
            url: string;
        };
        UpdateProfileDto: {
            firstName: string;
            lastName: string;
            /** @description The person ticked "I accept the terms" and "I confirm the privacy policy" */
            acceptLegal?: boolean;
        };
        SetPinDto: {
            /** @example 135790 */
            pin: string;
        };
        PinCheckDto: {
            /** @enum {string} */
            result: "correct" | "wrong" | "locked_out";
            /** @description Only for "wrong". */
            attemptsLeft?: number;
        };
        ChangePinDto: {
            currentPin: string;
            newPin: string;
        };
        WalletDto: {
            /** @example 3760 */
            balanceCents: number;
            /** @example 5000 */
            monthlyAllowanceCents: number;
            /** @description When the remaining balance expires: end of the month in Germany. */
            expiresAt: string;
            /** @description When the next monthly credit arrives; empty if no more credits (leaving or ended). */
            nextCreditAt: Record<string, never> | null;
        };
        WalletTransactionDto: {
            id: string;
            /** @enum {string} */
            type: "credit" | "payment" | "refund" | "expiry";
            amountCents: number;
            createdAt: string;
            /**
             * @description Short reference for the shop or support.
             * @example K7Q-4821
             */
            reference: string;
            shopId: Record<string, never> | null;
            shopName: Record<string, never> | null;
            /** @description Category slug of the shop, e.g. "bakery". */
            shopCategory: Record<string, never> | null;
        };
        WalletTransactionsPageDto: {
            items: components["schemas"]["WalletTransactionDto"][];
            /** @description Pass as "before" to load older transactions; empty when there are none. */
            nextBefore: Record<string, never> | null;
        };
        LookupCodeDto: {
            /**
             * @description Scanned QR text or the 6 digits typed by the employee
             * @example 418273
             */
            code: string;
        };
        PaymentRequestDto: {
            id: string;
            /** @description Location id of the shop */
            shopId: string;
            shopName: string;
            /** @description Category slug */
            shopCategory: string;
            /** @description What the purchase costs */
            purchaseTotalCents: number;
            /** @description What the voucher pays: the purchase, or the whole balance if it is less */
            voucherCents: number;
            /** @description Printed shop QR code: the shop still has to accept */
            needsShopAcceptance: boolean;
            expiresAt: string;
        };
        OpeningPeriodDto: {
            /** @description 1 = Monday … 7 = Sunday */
            weekday: number;
            /** @description Minutes after midnight */
            opensAt: number;
            /** @description Minutes after midnight */
            closesAt: number;
        };
        ShopDto: {
            /** @description Location id */
            id: string;
            name: string;
            /** @description Category slug, e.g. "bakery" */
            category: string;
            street: string;
            postalCode: string;
            city: string;
            latitude: number;
            longitude: number;
            description: string;
            imageUrl: Record<string, never> | null;
            openingHours: components["schemas"]["OpeningPeriodDto"][];
            /** @description Current deal, e.g. "10 % auf alle Kuchen" */
            offer: Record<string, never> | null;
        };
        LookupResultDto: {
            /**
             * @description "payment": the shop entered the amount; "shop": printed QR
             * @enum {string}
             */
            kind: "payment" | "shop";
            request?: components["schemas"]["PaymentRequestDto"];
            shop?: components["schemas"]["ShopDto"];
        };
        CreatePrintedQrPaymentDto: {
            /** @description Location id from the scanned shop */
            shopId: string;
            /** @example 5000 */
            amountCents: number;
        };
        ConfirmPaymentDto: {
            paymentRequestId: string;
            /** @description Random id from the app; a retry with the same id never pays twice */
            clientRequestId: string;
            /** @example 135790 */
            pin: string;
        };
        PaymentOutcomeDto: {
            /** @enum {string} */
            result: "completed" | "awaiting_shop" | "declined" | "timed_out" | "pin_wrong" | "pin_locked_out";
            /** @description Payment id, to check the status */
            paymentId?: string;
            /** @description Set when completed */
            transaction?: components["schemas"]["WalletTransactionDto"];
            /** @description Only for pin_wrong */
            attemptsLeft?: number;
        };
        CreatePaymentRequestDto: {
            checkoutPointId: string;
            /** @example 680 */
            amountCents: number;
        };
        CreatedPaymentRequestDto: {
            id: string;
            /** @example 418273 */
            shortCode: string;
            /** @description Text for the QR code */
            qrPayload: string;
            expiresAt: string;
        };
        PartnerPaymentDto: {
            id: string;
            reference: string;
            /** @enum {string} */
            status: "awaiting_shop" | "completed" | "declined" | "timed_out" | "refunded" | "partially_refunded";
            /** @description Paid by voucher */
            amountCents: number;
            /** @description Full purchase; the difference is paid at the till */
            purchaseTotalCents: number;
            createdAt: string;
        };
        PaymentRequestStatusDto: {
            /** @enum {string} */
            status: "open" | "used" | "expired" | "cancelled";
            payment?: components["schemas"]["PartnerPaymentDto"];
        };
        PartnerLocationDto: {
            id: string;
            name: string;
            street: string;
            postalCode: string;
            city: string;
            /** @description The till ("Kasse") for payment requests */
            tillId: Record<string, never> | null;
            /** @description Text of the printed shop QR code, e.g. "kollektivo:shop:…" */
            printedQrPayload: Record<string, never> | null;
        };
        PartnerShopDto: {
            partnerId: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "staff";
            /** @enum {string} */
            status: "applied" | "in_review" | "active" | "suspended";
            locations: components["schemas"]["PartnerLocationDto"][];
        };
        PartnerMeDto: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            shops: components["schemas"]["PartnerShopDto"][];
        };
        FavouritesDto: {
            /** @description Location ids */
            shopIds: string[];
        };
        PlacementDto: {
            id: string;
            /** @description Location id of the shop */
            shopId: string;
            startsAt: string;
            endsAt: string;
            /** @description Higher is shown first */
            priority: number;
            headline: Record<string, never> | null;
        };
        CreateTicketDto: {
            /** @enum {string} */
            topic: "payment" | "balance" | "account" | "shops" | "other";
            /** @description What happened (required unless a payment problem other than "other" is chosen) */
            message: string;
            /** @description Wallet transaction id of the payment this is about */
            transactionId?: string;
            /**
             * @description Only with transactionId
             * @enum {string}
             */
            problem?: "wrong_amount" | "charged_twice" | "refund_missing" | "other";
        };
        TicketCreatedDto: {
            /** @example KO-482913 */
            number: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    AuthController_checkInvite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteDto"];
                };
            };
        };
    };
    AuthController_sendSignInCode_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendSignInCodeDto"];
            };
        };
        responses: {
            /** @description The code was emailed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifySignInCode_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifySignInCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    DevicesController_register_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceDto"];
            };
        };
        responses: {
            /** @description This phone receives push notifications. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevicesController_unregister_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No more push notifications to this phone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LegalController_current_v1: {
        parameters: {
            query?: {
                language?: "de" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalDocumentDto"][];
                };
            };
        };
    };
    MeController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    MeController_deleteAccount_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted and anonymised; bookings are kept as the law requires. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_updateProfile_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    MeController_changePin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePinDto"];
            };
        };
        responses: {
            /** @description result "correct" means the new PIN is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinCheckDto"];
                };
            };
        };
    };
    MeController_createPin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPinDto"];
            };
        };
        responses: {
            /** @description PIN created. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_removePin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forgot PIN: removed; a new one is created after the next sign-in. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_checkPin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPinDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinCheckDto"];
                };
            };
        };
    };
    WalletController_getWallet_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletDto"];
                };
            };
        };
    };
    WalletController_getTransactions_v1: {
        parameters: {
            query?: {
                /** @description nextBefore from the previous page */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletTransactionsPageDto"];
                };
            };
        };
    };
    PaymentsController_lookup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookupCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResultDto"];
                };
            };
        };
    };
    PaymentsController_createPrintedQrPayment_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrintedQrPaymentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRequestDto"];
                };
            };
        };
    };
    PaymentsController_confirm_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPaymentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOutcomeDto"];
                };
            };
        };
    };
    PaymentsController_status_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOutcomeDto"];
                };
            };
        };
    };
    PaymentsController_statusForRequest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOutcomeDto"];
                };
            };
        };
    };
    ShopPaymentsController_createRequest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedPaymentRequestDto"];
                };
            };
        };
    };
    ShopPaymentsController_requestStatus_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRequestStatusDto"];
                };
            };
        };
    };
    ShopPaymentsController_pending_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPaymentDto"][];
                };
            };
        };
    };
    ShopPaymentsController_accept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPaymentDto"];
                };
            };
        };
    };
    ShopPaymentsController_decline_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPaymentDto"];
                };
            };
        };
    };
    PartnersController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerMeDto"];
                };
            };
        };
    };
    ShopsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopDto"][];
                };
            };
        };
    };
    ShopsController_favourites_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavouritesDto"];
                };
            };
        };
    };
    ShopsController_addFavourite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked as favourite */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopsController_removeFavourite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No longer a favourite */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopsController_placements_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementDto"][];
                };
            };
        };
    };
    ShopsController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopDto"];
                };
            };
        };
    };
    SupportController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCreatedDto"];
                };
            };
        };
    };
}
