/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/invites/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_checkInvite_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-in-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_sendSignInCode_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifySignInCode_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["DevicesController_register_v1"];
        post?: never;
        delete: operations["DevicesController_unregister_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/legal/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LegalController_current_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_get_v1"];
        put?: never;
        post?: never;
        delete: operations["MeController_deleteAccount_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MeController_updateProfile_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MeController_changePin_v1"];
        post: operations["MeController_createPin_v1"];
        delete: operations["MeController_removePin_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/pin/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MeController_checkPin_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getWallet_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getTransactions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_lookup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/printed-qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_createPrintedQrPayment_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_confirm_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_status_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/for-request/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_statusForRequest_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payment-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShopPaymentsController_createRequest_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payment-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopPaymentsController_requestStatus_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payment-requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShopPaymentsController_cancelRequest_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/pending-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopPaymentsController_pending_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payments/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShopPaymentsController_accept_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/payments/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShopPaymentsController_decline_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PartnersController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PartnerPaymentsController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/payments/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PartnerPaymentsController_csv_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopProfileController_get_v1"];
        put: operations["ShopProfileController_update_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/locations/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ShopProfileController_updateLocation_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/deal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ShopProfileController_setDeal_v1"];
        post?: never;
        delete: operations["ShopProfileController_removeDeal_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShopProfileController_setPhoto_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamController_list_v1"];
        put?: never;
        post: operations["TeamController_add_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/partner/shops/{partnerId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["TeamController_remove_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopsController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/favourites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopsController_favourites_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/favourites/{shopId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ShopsController_addFavourite_v1"];
        post?: never;
        delete: operations["ShopsController_removeFavourite_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopsController_placements_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ShopsController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/support/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SupportController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employer/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmployersController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employer/companies/{employerId}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmployeesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employer/companies/{employerId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EmployeesController_invite_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employer/companies/{employerId}/invites/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EmployeesController_inviteMany_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employer/companies/{employerId}/invites/{inviteId}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EmployeesController_resend_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employer/companies/{employerId}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["EmployeesController_cancel_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: Record<string, never>;
        CheckInviteDto: {
            /** @example KOLL2026 */
            code: string;
        };
        InviteDto: {
            code: string;
            employerName: string;
            email: string;
            firstName: string;
            lastName: string;
        };
        SendSignInCodeDto: {
            /** @example max.mustermann@muster-gmbh.example */
            email: string;
            /** @description Set when signing up with an employer invite. */
            inviteCode?: string;
            /**
             * @description Which app signs in: the employee app (default), the shop portal only (shop), or the web portal for shops and employers (portal). Each only accepts its own people.
             * @enum {string}
             */
            app?: "employee" | "shop" | "portal";
        };
        VerifySignInCodeDto: {
            /** @example max.mustermann@muster-gmbh.example */
            email: string;
            /** @description Set when signing up with an employer invite. */
            inviteCode?: string;
            /**
             * @description Which app signs in: the employee app (default), the shop portal only (shop), or the web portal for shops and employers (portal). Each only accepts its own people.
             * @enum {string}
             */
            app?: "employee" | "shop" | "portal";
            /** @example 246813 */
            code: string;
        };
        MeDto: {
            id: string;
            email: string;
            employerName: string;
            firstName: string;
            lastName: string;
            hasCompletedProfile: boolean;
            hasPaymentPin: boolean;
            /** @enum {string} */
            status: "active" | "ended" | "blocked";
            /** @description Set while leaving: last day the balance can be used (YYYY-MM-DD). */
            benefitEndsAt: string | null;
            /** @description Employer's workplace; distances are measured from here without location sharing. */
            workplaceLatitude: number | null;
            workplaceLongitude: number | null;
        };
        SessionDto: {
            /** @description Exchange with Firebase signInWithCustomToken, then send the ID token as Bearer. */
            firebaseCustomToken: string;
            user: components["schemas"]["MeDto"];
        };
        RegisterDeviceDto: {
            /** @description Firebase Cloud Messaging token */
            pushToken: string;
            /** @enum {string} */
            platform: "ios" | "android";
            /** @enum {string} */
            language: "de" | "en";
            /** @example 0.1.0 */
            appVersion?: string;
        };
        LegalDocumentDto: {
            /** @enum {string} */
            type: "terms" | "privacy";
            /** @example 2026-10 */
            version: string;
            /** @example de */
            language: string;
            url: string;
        };
        UpdateProfileDto: {
            firstName: string;
            lastName: string;
            /** @description The person ticked "I accept the terms" and "I confirm the privacy policy" */
            acceptLegal?: boolean;
        };
        SetPinDto: {
            /** @example 135790 */
            pin: string;
        };
        PinCheckDto: {
            /** @enum {string} */
            result: "correct" | "wrong" | "locked_out";
            /** @description Only for "wrong". */
            attemptsLeft?: number;
        };
        ChangePinDto: {
            currentPin: string;
            newPin: string;
        };
        WalletDto: {
            /** @example 3760 */
            balanceCents: number;
            /** @example 5000 */
            monthlyAllowanceCents: number;
            /** @description When the remaining balance expires: end of the month in Germany. */
            expiresAt: string;
            /** @description When the next monthly credit arrives; empty if no more credits (leaving or ended). */
            nextCreditAt: string | null;
        };
        WalletTransactionDto: {
            id: string;
            /** @enum {string} */
            type: "credit" | "payment" | "refund" | "expiry";
            amountCents: number;
            createdAt: string;
            /**
             * @description Short reference for the shop or support.
             * @example K7Q-4821
             */
            reference: string;
            shopId: string | null;
            shopName: string | null;
            /** @description Category slug of the shop, e.g. "bakery". */
            shopCategory: string | null;
        };
        WalletTransactionsPageDto: {
            items: components["schemas"]["WalletTransactionDto"][];
            /** @description Pass as "before" to load older transactions; empty when there are none. */
            nextBefore: string | null;
        };
        LookupCodeDto: {
            /**
             * @description Scanned QR text or the 6 digits typed by the employee
             * @example 418273
             */
            code: string;
        };
        PaymentRequestDto: {
            id: string;
            /** @description Location id of the shop */
            shopId: string;
            shopName: string;
            /** @description Category slug */
            shopCategory: string;
            /** @description What the purchase costs */
            purchaseTotalCents: number;
            /** @description What the voucher pays: the purchase, or the whole balance if it is less */
            voucherCents: number;
            /** @description Printed shop QR code: the shop still has to accept */
            needsShopAcceptance: boolean;
            expiresAt: string;
        };
        OpeningPeriodDto: {
            /** @description 1 = Monday … 7 = Sunday */
            weekday: number;
            /** @description Minutes after midnight */
            opensAt: number;
            /** @description Minutes after midnight */
            closesAt: number;
        };
        ShopDto: {
            /** @description Location id */
            id: string;
            name: string;
            /** @description Category slug, e.g. "bakery" */
            category: string;
            street: string;
            postalCode: string;
            city: string;
            latitude: number;
            longitude: number;
            description: string;
            imageUrl: string | null;
            openingHours: components["schemas"]["OpeningPeriodDto"][];
            /** @example 03573 123456 */
            phone: string | null;
            /** @example https://www.backstube-lindner.de/ */
            website: string | null;
            /** @description Current deal, e.g. "10 % auf alle Kuchen" */
            offer: string | null;
        };
        LookupResultDto: {
            /**
             * @description "payment": the shop entered the amount; "shop": printed QR
             * @enum {string}
             */
            kind: "payment" | "shop";
            request?: components["schemas"]["PaymentRequestDto"];
            shop?: components["schemas"]["ShopDto"];
        };
        CreatePrintedQrPaymentDto: {
            /** @description Location id from the scanned shop */
            shopId: string;
            /** @example 5000 */
            amountCents: number;
        };
        ConfirmPaymentDto: {
            paymentRequestId: string;
            /** @description Random id from the app; a retry with the same id never pays twice */
            clientRequestId: string;
            /** @example 135790 */
            pin: string;
        };
        PaymentOutcomeDto: {
            /** @enum {string} */
            result: "completed" | "awaiting_shop" | "declined" | "timed_out" | "pin_wrong" | "pin_locked_out";
            /** @description Payment id, to check the status */
            paymentId?: string;
            /** @description Set when completed */
            transaction?: components["schemas"]["WalletTransactionDto"];
            /** @description Only for pin_wrong */
            attemptsLeft?: number;
        };
        CreatePaymentRequestDto: {
            checkoutPointId: string;
            /** @example 680 */
            amountCents: number;
        };
        CreatedPaymentRequestDto: {
            id: string;
            /** @example 418273 */
            shortCode: string;
            /** @description Text for the QR code */
            qrPayload: string;
            expiresAt: string;
        };
        PartnerPaymentDto: {
            id: string;
            reference: string;
            /** @enum {string} */
            status: "awaiting_shop" | "completed" | "declined" | "timed_out" | "refunded" | "partially_refunded";
            /** @description Paid by voucher */
            amountCents: number;
            /** @description Full purchase; the difference is paid at the till */
            purchaseTotalCents: number;
            createdAt: string;
            /** @description Printed-QR payments waiting for the shop: answer before this time */
            acceptUntil?: string;
        };
        PaymentRequestStatusDto: {
            /** @enum {string} */
            status: "open" | "used" | "expired" | "cancelled";
            payment?: components["schemas"]["PartnerPaymentDto"];
        };
        PartnerLocationDto: {
            id: string;
            name: string;
            street: string;
            postalCode: string;
            city: string;
            /** @description The till ("Kasse") for payment requests */
            tillId: string | null;
            /** @description Text of the printed shop QR code, e.g. "kollektivo:shop:…" */
            printedQrPayload: string | null;
        };
        PartnerShopDto: {
            partnerId: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "staff";
            /** @enum {string} */
            status: "applied" | "in_review" | "active" | "suspended";
            locations: components["schemas"]["PartnerLocationDto"][];
        };
        PartnerMeDto: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            shops: components["schemas"]["PartnerShopDto"][];
        };
        PartnerPaymentTotalsDto: {
            count: number;
            /** @description Paid with KollektivO credit */
            amountCents: number;
            purchaseTotalCents: number;
            commissionCents: number;
        };
        PartnerPaymentRowDto: {
            id: string;
            /** @example DA7-5330 */
            reference: string;
            createdAt: string;
            locationId: string;
            /**
             * @description Code from the till or the printed QR sticker
             * @enum {string}
             */
            method: "till" | "printed_qr";
            /** @enum {string} */
            status: "awaiting_shop" | "completed" | "declined" | "timed_out" | "refunded" | "partially_refunded";
            /** @description Paid with KollektivO credit */
            amountCents: number;
            /** @description Whole purchase; the difference was paid at the till */
            purchaseTotalCents: number;
            /**
             * @description Basis points, 200 = 2 %
             * @example 200
             */
            commissionBps: number;
            /** @description Only for completed payments, else 0 */
            commissionCents: number;
        };
        PartnerPaymentsPageDto: {
            from: string;
            to: string;
            totals: components["schemas"]["PartnerPaymentTotalsDto"];
            items: components["schemas"]["PartnerPaymentRowDto"][];
            /** @description Pass as "before" for older payments; empty at the end */
            nextBefore: string | null;
        };
        ShopDealDto: {
            /** @example 10 % auf alle Kuchen */
            title: string;
            endsAt: string;
        };
        ShopProfileLocationDto: {
            id: string;
            name: string;
            street: string;
            postalCode: string;
            city: string;
            phone: string | null;
            openingHours: components["schemas"]["OpeningPeriodDto"][];
        };
        ShopProfileDto: {
            partnerId: string;
            name: string;
            /** @example bakery */
            category: string;
            description: string;
            website: string | null;
            imageUrl: string | null;
            deal: components["schemas"]["ShopDealDto"] | null;
            locations: components["schemas"]["ShopProfileLocationDto"][];
        };
        UpdateShopProfileDto: {
            description: string;
            /**
             * @description Empty to remove
             * @example www.backstube-lindner.de
             */
            website?: string;
        };
        OpeningPeriodInputDto: {
            /** @description 1 = Monday … 7 = Sunday */
            weekday: number;
            /** @description Minutes after midnight */
            opensAt: number;
            /** @description Minutes after midnight, after opensAt */
            closesAt: number;
        };
        UpdateShopLocationDto: {
            /**
             * @description Empty to remove
             * @example 03573 123456
             */
            phone?: string;
            /** @description Up to 3 periods per day (e.g. lunch break) */
            openingHours: components["schemas"]["OpeningPeriodInputDto"][];
        };
        SetShopDealDto: {
            /** @example 10 % auf alle Kuchen */
            title: string;
            /**
             * @description Last day (German time); default in one year
             * @example 2026-12-31
             */
            endsOn?: string;
        };
        TeamMemberDto: {
            userId: string;
            email: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "owner" | "staff";
            addedAt: string;
            /** @description Has signed in at least once (in the portal or the app) */
            hasSignedIn: boolean;
            /** @description The signed-in person */
            isYou: boolean;
        };
        AddTeamMemberDto: {
            /** @example kasse@backstube.example */
            email: string;
            firstName: string;
            lastName: string;
            /**
             * @description staff = till and payments; owner = everything
             * @enum {string}
             */
            role: "owner" | "staff";
        };
        FavouritesDto: {
            /** @description Location ids */
            shopIds: string[];
        };
        PlacementDto: {
            id: string;
            /** @description Location id of the shop */
            shopId: string;
            startsAt: string;
            endsAt: string;
            /** @description Higher is shown first */
            priority: number;
            headline: string | null;
        };
        CreateTicketDto: {
            /** @enum {string} */
            topic: "payment" | "balance" | "account" | "shops" | "other";
            /** @description What happened (required unless a payment problem other than "other" is chosen) */
            message: string;
            /** @description Wallet transaction id of the payment this is about */
            transactionId?: string;
            /**
             * @description Only with transactionId
             * @enum {string}
             */
            problem?: "wrong_amount" | "charged_twice" | "refund_missing" | "other";
        };
        TicketCreatedDto: {
            /** @example KO-482913 */
            number: string;
        };
        EmployerCompanyDto: {
            employerId: string;
            name: string;
            /**
             * @description owner = also manages the HR team
             * @enum {string}
             */
            role: "owner" | "hr";
            /** @enum {string} */
            status: "onboarding" | "active" | "ended";
            street: string;
            postalCode: string;
            city: string;
        };
        EmployerMeDto: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            companies: components["schemas"]["EmployerCompanyDto"][];
        };
        EmployeeRowDto: {
            /** @enum {string} */
            kind: "employee" | "invite";
            /** @description Employee id or invite id (see kind) */
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            personnelNumber: string | null;
            /** @example 5000 */
            monthlyAmountCents: number;
            /** @enum {string} */
            status: "invited" | "invite_expired" | "active" | "leaving" | "ended" | "blocked";
            /** @description YYYY-MM-DD */
            startedOn: string | null;
            /** @description Last day of the benefit (leavers), YYYY-MM-DD */
            benefitEndsOn: string | null;
            /** @description Invites: when the code expires */
            inviteExpiresAt: string | null;
        };
        InviteEmployeeDto: {
            /** @example max.mustermann@firma.de */
            email: string;
            firstName: string;
            lastName: string;
            /** @example 10427 */
            personnelNumber?: string;
            /**
             * @description Monthly credit in cents, 0 – 5000 (default 5000)
             * @example 5000
             */
            monthlyAmountCents?: number;
        };
        BulkInviteDto: {
            people: components["schemas"]["InviteEmployeeDto"][];
        };
        BulkInviteResultDto: {
            email: string;
            /** @enum {string} */
            result: "invited" | "already_member" | "already_invited" | "failed";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    AuthController_checkInvite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteDto"];
                };
            };
        };
    };
    AuthController_sendSignInCode_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendSignInCodeDto"];
            };
        };
        responses: {
            /** @description The code was emailed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifySignInCode_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifySignInCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    DevicesController_register_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceDto"];
            };
        };
        responses: {
            /** @description This phone receives push notifications. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevicesController_unregister_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No more push notifications to this phone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LegalController_current_v1: {
        parameters: {
            query?: {
                language?: "de" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalDocumentDto"][];
                };
            };
        };
    };
    MeController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    MeController_deleteAccount_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted and anonymised; bookings are kept as the law requires. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_updateProfile_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    MeController_changePin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePinDto"];
            };
        };
        responses: {
            /** @description result "correct" means the new PIN is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinCheckDto"];
                };
            };
        };
    };
    MeController_createPin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPinDto"];
            };
        };
        responses: {
            /** @description PIN created. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_removePin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forgot PIN: removed; a new one is created after the next sign-in. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_checkPin_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPinDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinCheckDto"];
                };
            };
        };
    };
    WalletController_getWallet_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletDto"];
                };
            };
        };
    };
    WalletController_getTransactions_v1: {
        parameters: {
            query?: {
                /** @description nextBefore from the previous page */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletTransactionsPageDto"];
                };
            };
        };
    };
    PaymentsController_lookup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookupCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResultDto"];
                };
            };
        };
    };
    PaymentsController_createPrintedQrPayment_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrintedQrPaymentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRequestDto"];
                };
            };
        };
    };
    PaymentsController_confirm_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPaymentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOutcomeDto"];
                };
            };
        };
    };
    PaymentsController_status_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOutcomeDto"];
                };
            };
        };
    };
    PaymentsController_statusForRequest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOutcomeDto"];
                };
            };
        };
    };
    ShopPaymentsController_createRequest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedPaymentRequestDto"];
                };
            };
        };
    };
    ShopPaymentsController_requestStatus_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRequestStatusDto"];
                };
            };
        };
    };
    ShopPaymentsController_cancelRequest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRequestStatusDto"];
                };
            };
        };
    };
    ShopPaymentsController_pending_v1: {
        parameters: {
            query?: {
                /** @description Only payments at this location */
                locationId?: string;
            };
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPaymentDto"][];
                };
            };
        };
    };
    ShopPaymentsController_accept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPaymentDto"];
                };
            };
        };
    };
    ShopPaymentsController_decline_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPaymentDto"];
                };
            };
        };
    };
    PartnersController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerMeDto"];
                };
            };
        };
    };
    PartnerPaymentsController_list_v1: {
        parameters: {
            query?: {
                /** @description First day (German time), default today */
                from?: string;
                /** @description Last day (German time), default = from */
                to?: string;
                /** @description Only payments at this location */
                locationId?: string;
                /** @description nextBefore from the previous page (list only, not CSV) */
                before?: string;
            };
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPaymentsPageDto"];
                };
            };
        };
    };
    PartnerPaymentsController_csv_v1: {
        parameters: {
            query?: {
                /** @description First day (German time), default today */
                from?: string;
                /** @description Last day (German time), default = from */
                to?: string;
                /** @description Only payments at this location */
                locationId?: string;
                /** @description nextBefore from the previous page (list only, not CSV) */
                before?: string;
            };
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    ShopProfileController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopProfileDto"];
                };
            };
        };
    };
    ShopProfileController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShopProfileDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopProfileController_updateLocation_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShopLocationDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopProfileController_setDeal_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetShopDealDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopProfileController_removeDeal_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopProfileController_setPhoto_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    photo?: string;
                };
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberDto"][];
                };
            };
        };
    };
    TeamController_add_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTeamMemberDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partnerId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopDto"][];
                };
            };
        };
    };
    ShopsController_favourites_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavouritesDto"];
                };
            };
        };
    };
    ShopsController_addFavourite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked as favourite */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopsController_removeFavourite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No longer a favourite */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopsController_placements_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementDto"][];
                };
            };
        };
    };
    ShopsController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopDto"];
                };
            };
        };
    };
    SupportController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCreatedDto"];
                };
            };
        };
    };
    EmployersController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployerMeDto"];
                };
            };
        };
    };
    EmployeesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRowDto"][];
                };
            };
        };
    };
    EmployeesController_invite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteEmployeeDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_inviteMany_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkInviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkInviteResultDto"][];
                };
            };
        };
    };
    EmployeesController_resend_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employerId: string;
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_cancel_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employerId: string;
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
